# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/admin"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/bosh_vpc"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/cdn_broker"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/cloud_watch"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/cloudfoundry"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/cloudfront"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/concourse"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/credhub"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/cvd_mirror"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/diego"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/dns"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/dns_logging"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/elasticache_broker_network"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/elasticsearch_broker"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/environment_dns"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/external_domain_broker"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/external_domain_broker_govcloud"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/external_domain_broker_tests"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/iam_role"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/iam_role_policy/aws_broker"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/iam_role_policy/blobstore"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/iam_role_policy/bosh"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/iam_role_policy/bosh_compilation"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/iam_role_policy/cf_blobstore"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/iam_role_policy/cloudwatch"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/iam_role_policy/compliance_role"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/iam_role_policy/concourse_iaas_worker"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/iam_role_policy/concourse_worker"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/iam_role_policy/ecr"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/iam_role_policy/elasticache_broker"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/iam_role_policy/logsearch_ingestor"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/iam_role_policy/s3_broker"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/iam_role_policy/self_managed_credentials"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/iam_user/billing_user"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/iam_user/cvd_sync"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/iam_user/ecr_user"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/iam_user/federalist_auditor"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/iam_user/health_check"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/iam_user/iam_cert_provision"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/iam_user/lets_encrypt"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/iam_user/limit_check_user"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/iam_user/rds_storage_alert"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/iam_user/s3_logstash"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/log_bucket"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/logsearch"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/opensearch_domain"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/monitoring"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/rds"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/rds_network"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/regionalmaster_dns"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/s3_bucket/encrypted_bucket"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/s3_bucket/kms_encrypted_bucket"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/s3_bucket/log_encrypted_bucket"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/s3_bucket/public_encrypted_bucket"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/shibboleth"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/smtp"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/stack/base"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/stack/spoke"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/vpc_peering"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/vpc_peering_sg"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/stacks/bootstrap"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/stacks/cloudfront"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/stacks/dns"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/stacks/external"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/stacks/main"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/stacks/managedaccount"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/stacks/regionalmasterbosh"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/stacks/tooling"
    schedule:
      interval: "weekly"
